### ISSUE TITLE
Update SwitchDevice to SwitchEntity class

### ISSUE THREAD

**Issue by wlouckx** [roblandry/netgear-enhanced-integration#2]
Looks like one of the later updates made SwitchDevice deprecated

From the logs:

> Log Details (WARNING)
> Logger: homeassistant.components.switch
> Source: components/switch/__init__.py:125
> Integration: Switch (documentation, issues)
> First occurred: 12:16:54 AM (1 occurrences)
> Last logged: 12:16:54 AM
> 
> SwitchDevice is deprecated, modify NetgearEnhancedSwitch to extend SwitchEntity

**Comment by roblandry** [comment]
Merged in #5
